# Advanced format with pattern validation
required_tags:
  Name:
    pattern: "^\\S+$"
  
  Environment:
    pattern: "^(dev|test|staging|prod)$"
  
  Owner:
    pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
  
  Project:
    pattern: "^[A-Z]{2,4}-[0-9]{3,6}$"
  
  CostCenter:
    pattern: "^CC-[0-9]{4}$"
