name: Deploy MkDocs to GitHub Pages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Needed to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5  # Using latest version
        with:
          fetch-depth: 0  # Fetch all history for proper gh-pages deployment

      - name: Set up Python
        uses: actions/setup-python@v5  # Using latest version
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pymdown-extensions mkdocs-minify-plugin

      - name: Deploy documentation from main to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force --message "Deploy docs from main branch {sha}"
